### ISSUE TITLE
No colors on excel spreadsheets

### ISSUE THREAD

**Issue by mjcolom-git** [nitschis/GreyEveTheme#3]
Excel shows no colors on spreadsheets: For example, set text color to green on a cell(s) , still show it(them) as white over black background . The version of excel does not matter, tested on office 2010, 2013, 2016 & 2019.

**Comment by nitschis** [comment]
It is a real pain in Windows to manage this.

Your best bet is to press Alt+Shift+PrtScn to switch to non-High Contrast when using excel.

I moved away from Windows a long time ago, but would still be interested in a solution to this problem. I don't have Office on my PC, so I can't really test this. 
With Visual Studio there is a trick by editing the registry, maybe the same thing can be done for Office?
https://www.reddit.com/r/VisualStudio/comments/7tbp6h/visual_studio_2017_high_contrast_theme_dark/
Please report back if you got it to work this way.

Another idea might be, to have another user with the default theme and then start the Office application with the runas command, I don't know if this works though, just an idea.
